version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    command: [ "air", "-c", "air.toml" ]
    environment:
      dbEngine: postgres
      dbUser: admin
      dbPassword: password
      dbName: user
      dbHost: postgres
      dbPort: 5432
      dbSSLMode: disable

volumes:
  postgres-data:


